### PR TITLE
feat: (ship ahead 3) deploy for review

### PR DESCRIPTION
**Pull request by uchilaka**
## Jira Card

[STORYAI-###](https://larcity.atlassian.net/browse/STORYAI-###)

## Summary

> Focus on what's important to note here. The Jira card should provide the rest the context.

## Screenshots (if appropriate):

```shell
Vercel CLI 32.2.5
Inspect: https://vercel.com/donnadieu/storyteller-ui/92kPJgNbkYYJSKzFtDJSJpVU8t37 [6s]
Preview: https://storyteller-ffja5txhg-donnadieu.vercel.app [6s]
To deploy to production (storyteller-ui.vercel.app +1), run `vercel --prod`
Vercel CLI 32.2.5
> Assigning alias storyteller-ffja5txhg-donnadieu.storysprout.app to deployment storyteller-ffja5txhg-donnadieu.vercel.app
> Certificate for storyteller-ffja5txhg-donnadieu.storysprout.app (cert_LUJ0g7W5yoaEPhoSMPL7y3qS) created [4s]
Deployment successful! Visit https://storyteller-ffja5txhg-donnadieu.storysprout.app to view your deployment.
```

## Review app(s)

- <storyteller-ui-git-###-donnadieu.vercel.app>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the README/confluence documentation.
- [ ] I have updated the relevant documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by uchilaka** [comment]
start a /review

**Review by Donnadieu — DISMISSED** [review]

**Review by Donnadieu — APPROVED** [review]

**Pull request merged**
